# Generated by Django 6.0.3 on 2026-04-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя режиссёра')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Режиссёр',
                'verbose_name_plural': 'Режиссёры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('publication_year', models.IntegerField(verbose_name='Год выхода')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='film_covers/', verbose_name='Постер фильма')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('age_limit', models.IntegerField(blank=True, verbose_name='Возрастное ограничение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='module_project.producer', verbose_name='Режиссёр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
