# Generated by Django 5.2.12 on 2026-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0002_alter_film_options_film_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
    ]
