# Generated by Django 5.2.12 on 2026-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_project', '0003_alter_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer_file',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл трейлера (MP4, WebM)', null=True, upload_to='film_trailers/', verbose_name='Файл трейлера'),
        ),
    ]
